services:
  - type: web
    name: lumina-updates
    env: python
    buildCommand: pip install flask
    startCommand: python server.py
    envVars:
      - key: ADMIN_KEY
        value: @Serise2000
      - key: PORT
        value: 10000
